LSPosed/LSPosed

- app/src/main/java/io/github/lsposed/manager/util/RebootUtil.java
* zygote will be automatically restrarted as surfacelinger
has 'onrestart restart zygote' in service definition since N.
> app: Don't restart zygote manually on soft reboot

- core/src/main/cpp/main/src/config_manager.cpp
```
* Without this commit, the lines are printed like this:
02-03 21:00:20.488   987   987 I LSPosed : scope of com.mhook.dialog.beta is:
02-03 21:00:20.488   987   987 I LSPosed : com.bug.zqq
02-03 21:00:20.488   987   987 I LSPosed :   com.tencent.mobileqq
02-03 21:00:20.488   987   987 I LSPosed :   com.heytap.themestore
02-03 21:00:20.488   987   987 I LSPosed :   com.mhook.dialog.beta
```
> [core] Align lines when printing module scope list

- app/src/main/res/xml/keep.xml
somehow R8 thinks that they are useless
> [app] Keep afs drawables

- core/src/main/cpp/external/yahfa/src/HookMain.cpp
* Although this flag is likely to change on future S release,
just keep R value for now because we don't want to break
present DPs. What's more, this flag is always used with
kAccCompileDontBother, so not removing it should not
be harmful.
https://android-review.googlesource.com/c/platform/art/+/1646010
> [core] Keep R value of kAccPreCompiled flag

- core/src/main/java/org/lsposed/lspd/service/LSPosedService.java
The event is needed to detect e.g. if a package has been frozen, but it
can also occur if components (e.g. receivers) are disabled/enabled. Ignore
the event in these cases.
> [core] Ignore PACKAGE_CHANGED for single components

- app/proguard-rules.pro
- app/src/main/java/org/lsposed/manager/Constants.java
- app/src/main/java/org/lsposed/manager/ui/activity/base/BaseActivity.java
- core/src/main/java/org/lsposed/lspd/hooker/XposedInstallerHooker.java
- core/src/main/java/org/lsposed/lspd/service/PackageService.java
Since we change the package name, we don't have to hook old manager
which use contants.
Since we have released new stable version, we should prepare for
randomize package name and therefore don't need to fix package name
mismatch.
> [core] Remove useless code

- core/src/main/java/org/lsposed/lspd/nativebridge/ClassLinker.java
* This is not even a native method.
> [core] Remove @FastNative annotation of onPostFixupStaticTrampolines()

- core/src/main/cpp/main/src/native_api.cpp
- core/src/main/java/de/robv/android/xposed/XposedInit.java
- No need to use `vector`. `list` is enough
- Someone calling `System.LoadLibrary` in the static field in java will miss the native hook, so reverse the loading order.
> [core] Refine native api

- core/magisk_module/customize.sh
* Which causes unzip fail because it becomes /data/adb/lspd//...
> [core] Remove trailing slash for /data/adb/lspd

- core/magisk_module/module.prop
Used to get the version code more clearly from the Magisk module list.
> Add versionCode to the 'version' displayed in the Magisk module

- core/magisk_module/customize.sh
- core/magisk_module/post-fs-data.sh
- core/magisk_module/service.sh
Some modules may stick `post-fs-data.sh` of Magisk (for example running `resetprop`), leaving daemon unstarted.
In such case, we should try to startup daemon in `service.sh` though it's a bit too late.
> [core] Startup daemon in service.sh if post-fs-data.sh stucks

- core/src/main/java/org/lsposed/lspd/nativebridge/ModuleLogger.java
* It can only be NULL when in system_server.
> [core] Correct process name for android in module log

- app/src/main/java/org/lsposed/manager/util/ModuleUtil.java
* To get a reliable enabled status, we have to rely on
backend every time a module is uninstalled from
the manager.
> [app] Call getEnabledModules() in reloadSingleModule()

- core/src/main/aidl/org/lsposed/lspd/service/ILSPApplicationService.aidl
- core/src/main/java/org/lsposed/lspd/config/LSPApplicationServiceClient.java
- core/src/main/java/org/lsposed/lspd/core/Main.java
- core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java
- core/src/main/java/org/lsposed/lspd/service/LSPApplicationService.java
Some OS, like MIUI, inject other loaded apk to manager and will
cause annoying warnings
> [core] Check loadedApk package name when getting manager binder

- build.gradle.kts
Safe-Args now depends on Android Gradle Plugin 4.2.0. This means you should no longer get the using applicationIdTextResource warning. (I6d67b, b/172824579)
> [gradle] Suppress applicationIdTextResource warning

- core/src/main/java/org/lsposed/lspd/service/BridgeService.java
`sendToBridge` stucks the binder thread so that
`ActivityManagerService`'s receipent won't be called
https://github.com/LSPosed/LSPosed/blob/547c512546f95d11f8f48b809e4c7a1e107a6891/core/src/main/java/org/lsposed/lspd/service/ActivityManagerService.java#L45-L55
> [core] Fix broadcast receiver after soft reboot

- app/src/main/java/org/lsposed/manager/ui/fragment/RepoFragment.java
```
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object N8.c' on a null object reference
at org.lsposed.manager.ui.fragment.RepoFragment.g1(:1)
```
> [app] Fix crash

- core/src/main/java/org/lsposed/lspd/yahfa/dexmaker/DynamicBridge.java
Though the caller of `dexMaker` is synchronized, I still encounter thread confiction.
> [core] Fix rare condiction

- core/src/main/java/de/robv/android/xposed/XposedInit.java
if the target application with 32-bit native libraries only, we don't need 64-bit nativepath included
> [core] Compatible with applications with 32-bit native libraries only

- core/src/main/aidl/org/lsposed/lspd/service/ILSPApplicationService.aidl
- core/src/main/java/org/lsposed/lspd/config/ApplicationServiceClient.java
- core/src/main/java/org/lsposed/lspd/config/LSPApplicationServiceClient.java
- core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java
- core/src/main/java/org/lsposed/lspd/service/LSPApplicationService.java
```java
@Override public boolean requestManagerBinder(java.lang.String packageName, java.lang.String path, android.os.IBinder[] binder) throws android.os.RemoteException
{
android.os.Parcel _data = android.os.Parcel.obtain();
android.os.Parcel _reply = android.os.Parcel.obtain();
boolean _result;
try {
_data.writeInterfaceToken(DESCRIPTOR);
_data.writeString(packageName);
_data.writeString(path);
if ((binder==null)) {
_data.writeInt(-1);
}
else {
_data.writeInt(binder.length);
}
boolean _status = mRemote.transact(Stub.TRANSACTION_requestManagerBinder, _data, _reply, 0);
if (!_status) {
if (getDefaultImpl() != null) {
return getDefaultImpl().requestManagerBinder(packageName, path, binder);
}
}
_reply.readException();
_result = (0!=_reply.readInt());
binder = _reply.createBinderArray();
} …
```
> [core] AIDL array copy bug workaround

- core/src/main/java/org/lsposed/lspd/service/PackageService.java
Some apps may not create their deviceProtectedDataDir so don't check their existence.
Fix #833
> [core] Fix some apps not showing

- app/proguard-rules.pro
It's required only when R8 full mode is enabled. 
Do NOT merge this until confirmed we cannot fix R8 full mode. Close #985 .
> [app] No need to keep EnclosingMethod when R8 full mode disabled

- core/src/main/cpp/daemon/logcat.cpp
It's an ASOP's bug that tag len is 1 larger
> [core] Fix logcat tag len

- .github/workflows/core.yml
Omit commit messages if length exceeds 1024, replace it with a commit URL
> Fix `Post to channel` fails

- app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/xml-v29/prefs.xml
- app/src/main/res/xml/prefs.xml
When a language is added no need update arrays in preference.
For example after the language fa has been added this doesn't exist in the listpreference.
I don't know if is better move the method getAppLanguages in some class org.lsposed.manager.util
Maybe is better remove also the array string-array language and add @string/follow_system programmatically to entries
> [app] generate at runtime list of languages supported by app

- core/src/main/cpp/external/yahfa/include/HookMain.h
- core/src/main/cpp/external/yahfa/src/HookMain.cpp
- core/src/main/cpp/main/src/jni/yahfa.cpp
- core/src/main/java/org/lsposed/lspd/core/yahfa/HookMain.java
- core/src/main/java/org/lsposed/lspd/nativebridge/Yahfa.java
The data_ member is used to save a profiling info which used for optimizing and may cause some crashes. Just clear the member to avoid this.
Edit and commit in web editor, not tested. Please test before merging.
May fix #1144
> [core] Clear ProfilingInfo in backup method

- app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java
Is not a real fix but only a workaround. I can't reproduce the issue.
If the resource Settings is not found, return only an arraylist with english, so in the list of avaiable languages will be only "Follow the system" and "English"
> Fix for #1250

- core/src/main/java/org/lsposed/lspd/service/ActivityManagerService.java
- core/src/main/java/org/lsposed/lspd/service/LSPosedService.java
For oddo Android 9, if activityController is set too earilier, it
crashes system server. So move the set latter
> [core] Move `setActivityController` to boot complete

- .github/workflows/core.yml
This can get rid of legacy cmake config which always adds `-g` to build and thus reduce the size of debug build.
> Use cmake 3.21+

- core/src/main/java/org/lsposed/lspd/nativebridge/HookBridge.java
- core/src/main/jni/src/jni/hook_bridge.cpp
Since we have prevented Method.invoke() being hooked, directly calling Method.invoke() is safe.
> No need to implement Method.invoke ourselves

- daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java
- daemon/src/main/java/org/lsposed/lspd/service/LSPosedService.java
- hiddenapi/stubs/src/main/java/android/app/INotificationManager.java
When the Xposed Module was installed, LSPosed will send a notification that the module has not yet been activated. At this time, if the module is uninstalled and the user without clearing the notification by hand, the notification will not be auto cleared.
Also, I found that every time a new module is installed, the previous notification that the module is not activated will be replaced.
This change will probably resolve those issue.
> Fix the notification push issue after Xposed Module installation or removed

- daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java
- daemon/src/main/java/org/lsposed/lspd/service/LSPosedService.java
- hiddenapi/stubs/src/main/java/android/app/INotificationManager.java
Fix the bug of repeated push notification of module activation in the previous version, and fix the bug of repeated push notification after the module is uninstalled
> Fix the Xposed Module notification repeated push problem and the other problem

- daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java
With webview on Android 13 Beta (at least on Google Pixel devices), webview expects to be able to read from a randomly generated temp directory:
/data/user/0/com.android.shell/cache/.com.google.Chrome.XXXXXX (deleted)
Before this change, the root of the cache directory is labeled with `shell_data_file` and `Chrome_ChildIOT` is not permitted read access to the temp directory:
05-12 10:59:48.728 13692 13692 W Chrome_ChildIOT: type=1400 audit(0.0:258): avc: denied { read } for path=2F646174612F757365722F302F636F6D2E616E64726F69642E7368656C6C2F63616368652F2E636F6D2E676F6F676C652E4368726F6D652E5965394D6433202864656C6574656429 dev="dm-47" ino=230834 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=file permissive=0
> LSPManagerService: Change SELinux label of entire cache directory (#1933)

- core/src/main/java/de/robv/android/xposed/XposedBridge.java
- daemon/src/main/java/org/lsposed/lspd/service/ConfigFileManager.java
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
at com.mediatek.res.AsyncDrawableCache.putCacheList(AsyncDrawableCache.java:165)
at com.mediatek.res.ResOptExtImpl.putCacheList(ResOptExtImpl.java:69)
at android.content.res.ResourcesImpl.cacheDrawable(ResourcesImpl.java:800)
at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:737)
at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:307)
at android.content.res.Resources.loadDrawable(Resources.java:1017)
at android.content.res.Resources.getDrawableForDensity(Resources.java:1005)
at android.content.res.Resources.getDrawable(Resources.java:944)
at …
```
> Fix resource hook on MediaTek

- daemon/src/main/java/org/lsposed/lspd/util/FakeContext.java
```java
try {
this.mSystemUIContext = context.createPackageContext(AudioConstants.SYSTEMUI_PACKAGE_NAME, 0);
} catch (PackageManager.NameNotFoundException e) {
} catch (SecurityException e2) {
}
if (this.mSystemUIContext == null) {
this.mSystemUIContext = context;
}
```
> Fix notification on samsung

- core/src/main/java/de/robv/android/xposed/XposedBridge.java
a typo in the class name that caused afterHook to not work on the new api
> Typo in `AfterHooker` class name

- app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java
- app/src/main/java/org/lsposed/manager/util/ShortcutUtil.java
Workaround for Android 14 PB3: no callback from `requestPinShortcut`
> Reset notification preference when resume

- core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java
https://github.com/rovo89/XposedBridge/commit/2ca8d5eb7d0bcf251490f3192286877d4a4dfea8
Restore original xposed behavior
> Skip secondary classloaders that do not include code

- daemon/src/main/java/org/lsposed/lspd/service/ServiceManager.java
ActivityThread#systemMain -> ActivityThread#attach will also change the process name to 'system_process', so that there are two 'system_process' processes in the system.
https://android.googlesource.com/platform/frameworks/base/+/0e40462e11d27eb859b829b112cecb8c6f0d7afb/core/java/android/app/ActivityThread.java#5119
> Fix the 'lspd' process name

- .github/dependabot.yml
so that dependabot will only open one PR for multiple dependencies update.
> Group all maven dependencies
