app/proguard-rules.pro, app/src/main/java/io/github/lsposed/manager/adapters/ScopeAdapter.java, app/src/main/java/io/github/lsposed/manager/util/ModuleUtil.java
=> Fix app list sort comparators

core/src/main/cpp/main/src/jni/pending_hooks.cpp
=> [core] Lock critical section

core/src/main/java/io/github/lsposed/lspd/yahfa/dexmaker/HookerDexMaker.java
https://github.com/LSPosed/LSPosed/issues/58#issuecomment-772397204
=> Fix duplicate declare when cache fails

app/src/main/java/io/github/lsposed/manager/ui/activity/BaseActivity.java, app/src/main/java/io/github/lsposed/manager/ui/activity/SettingsActivity.java, app/src/main/res/values-night/styles.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/styles.xml
=> Allow turning off black dark theme when md2 enabled

app/src/main/java/io/github/lsposed/manager/Constants.java, app/src/main/java/io/github/lsposed/manager/ui/activity/SettingsActivity.java, app/src/main/java/io/github/lsposed/manager/util/BackupUtils.java, app/src/main/java/io/github/lsposed/manager/util/ModuleUtil.java, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs.xml
=> Add support for backing up and restoring module list and scope list

app/src/main/res/values-zh-rTW/strings.xml
Up-to-date Traditional Chinese Strings
=> Update Traditional Chinese Strings

app/src/main/java/io/github/lsposed/manager/adapters/AppHelper.java, app/src/main/java/io/github/lsposed/manager/adapters/ScopeAdapter.java, app/src/main/java/io/github/lsposed/manager/ui/activity/AppListActivity.java, app/src/main/java/io/github/lsposed/manager/ui/activity/SettingsActivity.java, app/src/main/java/io/github/lsposed/manager/util/BackupUtils.java, app/src/main/java/io/github/lsposed/manager/util/ModuleUtil.java, app/src/main/res/menu/menu_app_list.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Backup file is gzipped json string now
=> Add support for backup and restore single module scope

app/src/main/java/io/github/lsposed/manager/ui/activity/LogsActivity.java
https://github.com/LSPosed/LSPosed/issues/58#issuecomment-774026586
=> [app] Fix log reader crash

core/src/main/cpp/main/src/config_manager.cpp, core/src/main/cpp/main/src/config_manager.h
=> [core] Check variant_path when updating config file

app/src/main/java/io/github/lsposed/manager/App.java, app/src/main/java/io/github/lsposed/manager/receivers/EdServiceReceiver.java, app/src/main/java/io/github/lsposed/manager/ui/activity/ModulesActivity.java, app/src/main/java/io/github/lsposed/manager/util/NotificationUtil.java, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Open app list instead of module list
=> [app] Update notification util

app/src/main/java/name/mikanoshi/customiuizer/holidays/HolidayHelper.java
*This will not happen until next year
=> Fix a newyear header crash

app/src/main/res/values-nl/strings.xml
=> Add Dutch translation

app/build.gradle, app/proguard-rules.pro, app/src/main/java/io/github/lsposed/manager/ui/fragment/StatusDialogBuilder.java
which will make R8 confused and crazy
=> [app] Remove the use of hidden api

app/src/main/res/values-ru/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml
=> i18n update

core/src/main/aidl/io/github/lsposed/lspd/service/ILSPApplicationService.aidl, core/src/main/aidl/io/github/lsposed/lspd/service/ILSPosedService.aidl, core/src/main/cpp/main/src/service.cpp, core/src/main/cpp/main/src/service.h, core/src/main/java/io/github/lsposed/lspd/config/LSPApplicationServiceClient.java, core/src/main/java/io/github/lsposed/lspd/core/Main.java, core/src/main/java/io/github/lsposed/lspd/service/BridgeService.java, core/src/main/java/io/github/lsposed/lspd/service/ConfigManager.java, core/src/main/java/io/github/lsposed/lspd/service/LSPApplicationService.java, core/src/main/java/io/github/lsposed/lspd/service/LSPosedService.java, core/src/main/java/io/github/lsposed/lspd/service/ServiceManager.java
=> [core] Send app binder when requesting binder

app/src/main/res/values-zh-rTW/strings.xml
=> zh_TW update

app/src/main/res/values-zh-rTW/strings.xml
Update zh-TW translation from [https://github.com/LSPosed/LSPosed/commit/d0bd6c1be380e92dd4b9202d2c92c6ff6958734c#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103](https://github.com/LSPosed/LSPosed/commit/d0bd6c1be380e92dd4b9202d2c92c6ff6958734c#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103)
=> Update zh-TW translation

app/src/main/java/io/github/lsposed/manager/ui/fragment/StatusDialogBuilder.java, build.gradle
=> [app] Fix android codename

app/build.gradle, app/src/main/res/values-fr/strings.xml
Ready to be merged into master branch.
Nice work!
=> Adding French translation

app/src/main/java/io/github/lsposed/manager/ui/activity/MainActivity.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> [app] Fix activation string

app/src/main/res/values-ko/strings.xml
=> Update Korean translation

core/src/main/cpp/main/src/service.cpp
=> [core] Prevent bootloop when rirud is dead

app/build.gradle.kts, app/src/main/res/values-de/strings.xml
I have added a german translation for the LSPosed manager.
I tested it, and everything should be able to merge.
=> Add German translation

core/src/main/cpp/main/src/context.cpp, core/src/main/cpp/main/src/context.h, core/src/main/java/io/github/lsposed/lspd/core/yahfa/HookMain.java, core/src/main/java/io/github/lsposed/lspd/service/ConfigManager.java, core/src/main/java/io/github/lsposed/lspd/service/LSPManagerService.java, core/template_override/customize.sh, core/template_override/post-fs-data.sh, core/template_override/sepolicy.rule, hiddenapi-stubs/src/main/java/android/os/SELinux.java, manager-service/src/main/aidl/io/github/lsposed/lspd/ILSPManagerService.aidl
=> [core] Check sepolicy in backend & try livepatch

app/src/main/res/values-nl/strings.xml
Strings updated for the new and latest LSPosed manager with dutch translations
=> New updated strings

app/src/main/res/values-nl/strings.xml
=> Revert "New updated strings"

app/src/main/res/values-nl/strings.xml
all good SEpolicy etc is inside and all is good now
=> fixed and updated strings.xml with Dutch translation

app/src/main/java/org/lsposed/manager/ui/activity/MainActivity.java, app/src/main/res/layout/dialog_about.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> [app] Add translators to about dialog

app/src/main/java/org/lsposed/manager/ui/activity/RepoActivity.java
* Or it will crash when sorted by released time.
=> [app] Discard modules without releases when filtering

app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_untranslatable.xml
=> [app] Move untranslatable strings into standalone file

core/template_override/customize.sh, core/template_override/util_functions.sh
* Because magisk --path is not available till this version.
=> [core] Actually require Magisk v21+

core/build.gradle.kts
=> [core] Set optimize flags correctly

core/template_override/riru.sh
Fix https://github.com/Magisk-Modules-Repo/riru-core/pull/4
=> [core] Fix typo

app/src/main/java/org/lsposed/manager/App.java, app/src/main/java/org/lsposed/manager/util/DoHDNS.java
https://github.com/tuna/collection/issues/189
=> Add dnspod

app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rHK/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
更新中文翻译：
1. 更新 TW 翻译
2. 将 CN 及 HK 翻译改成 [英文](https://github.com/LSPosed/LSPosed/blob/master/app/src/main/res/values/strings.xml) 的顺序
https://github.com/LSPosed/LSPosed/blob/master/app/src/main/res/values/strings.xml
Update Chinese translation:
1. Update zh-TW translation.
2. Change zh-CN and zh-HK strings sort by English file. 
https://github.com/LSPosed/LSPosed/blob/master/app/src/main/res/values/strings.xml
=> Update Chinese translation

app/src/main/java/org/lsposed/manager/adapters/ScopeAdapter.java, app/src/main/java/org/lsposed/manager/ui/activity/AppListActivity.java
=> [app] Fix crash in searching

core/src/main/java/org/lsposed/lspd/service/BridgeService.java
=> [core] Fix register receiver permission

app/src/main/java/org/lsposed/manager/ConfigManager.java, app/src/main/java/org/lsposed/manager/ui/activity/ModulesActivity.java, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, core/src/main/java/org/lsposed/lspd/service/PackageService.java
=> Install to profiles

app/build.gradle.kts, app/src/main/res/values-es/strings.xml
Hello! I found this repository and saw some translations into other languages. I'm a native Spanish speaker who has previously translated documents into my native language so I decided to translate the strings of this repository from English to Spanish. If anything, please let me know.
=> Add Spanish translation

app/src/main/res/values-nl/strings.xml
add some new lines for icon app option
=> Updated NL Strings

app/src/main/res/values-zh-rTW/strings.xml
修复 
https://github.com/LSPosed/LSPosed/commit/2228ef23512423d4da23918d72ed8193682e1381
未修改的部分
=> [app] Fix non-positional format string

app/src/main/java/org/lsposed/manager/util/ModuleUtil.java
* This ensures that enabled modules will be updated together
with installed modules.
=> [app] Query enabled modules in reloadInstalledModules()

app/src/main/java/org/lsposed/manager/util/ModuleUtil.java, core/src/main/java/android/app/AndroidAppHelper.java, core/src/main/java/android/content/res/XModuleResources.java, core/src/main/java/android/content/res/XResources.java, core/src/main/java/de/robv/android/xposed/PendingHooks.java, core/src/main/java/de/robv/android/xposed/XSharedPreferences.java, core/src/main/java/de/robv/android/xposed/XposedBridge.java, core/src/main/java/de/robv/android/xposed/XposedHelpers.java, core/src/main/java/de/robv/android/xposed/callbacks/XCallback.java, core/src/main/java/org/lsposed/lspd/config/LSPApplicationServiceClient.java, core/src/main/java/org/lsposed/lspd/core/Main.java, core/src/main/java/org/lsposed/lspd/deopt/PrebuiltMethodsDeopter.java, core/src/main/java/org/lsposed/lspd/hooker/HandleBindAppHooker.java, core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java, core/src/main/java/org/lsposed/lspd/hooker/StartBootstrapServicesHooker.java, core/src/main/java/org/lsposed/lspd/hooker/XposedInstallerHooker.java, core/src/main/java/org/lsposed/lspd/service/ActivityManagerService.java, core/src/main/java/org/lsposed/lspd/service/BridgeService.java, core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, core/src/main/java/org/lsposed/lspd/service/LSPosedService.java, core/src/main/java/org/lsposed/lspd/service/PowerService.java, core/src/main/java/org/lsposed/lspd/service/UserService.java, core/src/main/java/org/lsposed/lspd/util/ModuleLogger.java, core/src/main/java/org/lsposed/lspd/yahfa/dexmaker/DynamicBridge.java, core/src/main/java/org/lsposed/lspd/yahfa/hooker/YahfaHooker.java
* Final step to get a correct status of enabled modules.
=> [app] Call reloadInstalledModules() unconditionally

core/src/main/java/org/lsposed/lspd/hooker/StartBootstrapServicesHooker.java
* We don't force recompilation of pre-optimized
APKs now so this is useless and does not even
work as performDexOpt() hook was removed.
=> [core] Drop useless hook for Huawei

core/src/main/java/org/lsposed/lspd/service/ActivityManagerService.java, core/src/main/java/org/lsposed/lspd/service/PackageService.java, hiddenapi-stubs/src/main/java/android/app/IActivityManager.java
=> [core] Fix #674

core/src/main/java/org/lsposed/lspd/service/ActivityManagerService.java, core/src/main/java/org/lsposed/lspd/service/LSPosedService.java, hiddenapi-stubs/src/main/java/android/app/IActivityManager.java
=> [core] Unblock receiver by calling finish receiver

app/src/main/java/org/lsposed/manager/ui/fragment/RepoFragment.java
=> [app] Discard modules without releases again

app/src/main/java/org/lsposed/manager/ui/fragment/ModulesFragment.java, app/src/main/java/org/lsposed/manager/ui/fragment/RepoItemFragment.java
`app:fitsSystemWindowsInsets="top|bottom"` should be placed on `viewPager` otherwise it's too late to set the padding.
=> [app] Fix scroll bar of module fragment from shortcut

core/src/main/cpp/.clang-tidy, core/src/main/cpp/main/src/symbol_cache.cpp
=> [core] Fix native hook

app/build.gradle.kts, app/src/main/res/values-ja/strings.xml
Hello I'd made Japanese translation for your LSPosed.
If you like it, please pull this.
=> Added Japanese Translation

core/src/main/java/org/lsposed/lspd/util/InMemoryDelegateLastClassLoader.java, hiddenapi-bridge/src/main/java/hidden/ByteBufferDexClassLoader.java, hiddenapi-stubs/src/main/java/dalvik/system/BaseDexClassLoader.java
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r39:art/runtime/jni/java_vm_ext.cc;l=1181;drc=dc77ca3d54bd83faee98591474728a5e3ecfc551
=> Add getLdLibraryPath

app/src/main/res/values-it/strings.xml
Added missing strings and made some minor fixes/improvements to existing translations.
Can I have more details on what you mean with _"Modules may **invalidate** occasionally"_ in `system_prop_incorrect` string?
I tried to guess its meaning in order to make an understandable translation, but I'm not sure if it's correct (my Italian translation would sound more similar to _"Modules may end up being invalid occasionally"_).
=> [app] Update Italian translation

app/src/main/res/values-it/strings.xml
Found a couple of mistakes in my previous PR.
=> [app] More adjustments to Italian translation

core/src/main/aidl/org/lsposed/lspd/models/ModuleConfig.aidl, core/src/main/java/de/robv/android/xposed/XposedInit.java, core/src/main/java/org/lsposed/lspd/service/ConfigManager.java, core/src/main/java/org/lsposed/lspd/util/LspModuleClassLoader.java
=> [core] pre load module dexes

app/src/main/java/org/lsposed/manager/ui/fragment/RepoItemFragment.java, app/src/main/res/layout/fragment_pager.xml, app/src/main/res/values-zh-rCN/strings.xml
The repository item fragment and modules fragment use the same layout file, the previous commit missed this.
The changes in fragment_pager.xml are just formatting code.
=> [app] Fix the tabLayout style of the repository item fragment

core/src/main/java/org/lsposed/lspd/util/LspModuleClassLoader.java, hiddenapi-bridge/src/main/java/hidden/ByteBufferDexClassLoader.java, hiddenapi-stubs/src/main/java/com/android/internal/os/RuntimeInit.java, hiddenapi-stubs/src/main/java/com/android/internal/os/ZygoteInit.java, hiddenapi-stubs/src/main/java/dalvik/system/BaseDexClassLoader.java
=> [core] Remove workaround

app/src/main/res/values-zh-rTW/strings.xml
=> Update zh_TW transition

app/src/main/AndroidManifest.xml, app/src/main/java/org/lsposed/manager/App.java, core/src/main/java/org/lsposed/lspd/service/LSPosedService.java
=> Revert "[app] Dynamic registration receiver"

app/src/main/java/org/lsposed/manager/App.java, app/src/main/java/org/lsposed/manager/ui/activity/CrashReportActivity.java, core/src/main/java/org/lsposed/lspd/util/ModuleLogger.java
=> Use java8 time API

core/src/main/java/org/lsposed/lspd/service/ConfigManager.java
=> [core] Fix apk path not updated again

core/src/main/cpp/daemon/logcat.cpp, core/src/main/java/org/lsposed/lspd/service/LogcatService.java
More accurate and in time and don't need to grab file size every time.
=> [log] Check log size in native

gradle.properties
=> Revert "Enable R8 full mode"

core/src/main/cpp/daemon/logcat.cpp, core/src/main/java/org/lsposed/lspd/service/LogcatService.java
=> Revert "[core] Fix logcat"

core/src/main/java/org/lsposed/lspd/service/ConfigManager.java
=> [core] Fix create index

app/src/main/java/org/lsposed/manager/ui/fragment/RepoFragment.java
Fix crash caused by preloading WebView when fragment is deteched
=> [app] Remove pending preload action when detaching

core/src/main/cpp/daemon/logcat.cpp
=> [core] Try manually start logd

core/src/main/java/org/lsposed/lspd/service/ServiceManager.java
=> [core] DO NOT call pm when pm is not yet fully ready

core/src/main/cpp/daemon/logcat.cpp
This fixes the high CPU usage of logd
=> [core] Reduce log buffer size

core/src/main/aidl/org/lsposed/lspd/models/PreLoadedApk.aidl, core/src/main/java/de/robv/android/xposed/XposedInit.java
=> Revert "[core] fix loading embedded module so"

core/src/main/cpp/main/src/elf_util.cpp, core/src/main/cpp/main/src/symbol_cache.cpp
=> [core] Fix `failed to open [anon:linker_alloc]`

core/src/main/cpp/main/src/elf_util.cpp
> f2612000-f262f000 r--p 00000000 07:38 25                                 /apex/com.android.runtime/bin/linker
buff[0] != '/'
=> [core] Fix elf name match

app/src/main/res/xml-v29/prefs.xml
=> [app] Hide unavailable settings on lower versions of Android

core/src/main/cpp/main/src/main.cpp
=> [core] Set GID in specializeAppProcessPre() as well

app/src/main/AndroidManifest.xml
Move license starting line to next line.
=> Properly fomat AndroidManifest.xml

core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, gradle.properties
=> Disable new resource shinker to avoid string strip

core/src/main/cpp/external/yahfa/include/HookMain.h, core/src/main/cpp/external/yahfa/src/HookMain.cpp, core/src/main/cpp/main/src/jni/yahfa.cpp, core/src/main/java/org/lsposed/lspd/core/yahfa/HookMain.java, core/src/main/java/org/lsposed/lspd/nativebridge/Yahfa.java
=> Revert "[core] Clear ProfilingInfo in backup method"

app/build.gradle.kts, build.gradle.kts, core/build.gradle.kts
=> [gradle] Fallback to stable AGP

app/src/main/java/org/lsposed/manager/ConfigManager.java, app/src/main/java/org/lsposed/manager/ui/fragment/RepoItemFragment.java, app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java, app/src/main/java/org/lsposed/manager/ui/widget/LinkifyTextView.java, app/src/main/java/org/lsposed/manager/util/theme/ThemeColorPreference.java, core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, core/src/main/java/org/lsposed/lspd/util/MetaDataReader.java, core/src/main/java/org/lsposed/lspd/util/ParasiticManagerHooker.java
Reduce warnings in the IDE
Tested in the Android 11 AVD (Debug build)
=> Require non null

app/src/main/java/org/lsposed/manager/App.java, app/src/main/java/org/lsposed/manager/util/ModuleUtil.java, core/src/main/java/org/lsposed/lspd/service/ConfigManager.java, core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, core/src/main/java/org/lsposed/lspd/service/LSPosedService.java
Broadcast immediately after a package state change
=> Fix the module status in the manager after module changes

core/src/main/java/org/lsposed/lspd/service/ConfigManager.java, core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java
=> [core] Fix the module scope setting on first installation

core/src/main/java/org/lsposed/lspd/service/ActivityController.java, hiddenapi-stubs/src/main/java/android/app/IActivityController.java
=> [core] Fix 360 IActivityController

core/src/main/cpp/main/src/context.cpp, core/src/main/java/org/lsposed/lspd/core/Main.java, hiddenapi-bridge/build.gradle.kts, hiddenapi-bridge/src/main/java/hidden/HiddenApiBridge.java, hiddenapi-stubs/src/main/java/dalvik/system/VMRuntime.java
https://cs.android.com/android/platform/superproject/+/master:art/runtime/oat_file_assistant.cc;drc=7fa70866414df11ef0c9d8eca3e6c23788e8c9d8;l=484
=> [core] Allow vdex speedup for InMemoryDex

core/src/main/cpp/main/Android.mk, core/src/main/cpp/main/api/zygisk_main.cpp
=> Revert "[zygisk] Use ASharedMemory"

app/src/main/java/org/lsposed/manager/repo/RepoLoader.java, app/src/main/java/org/lsposed/manager/ui/fragment/HomeFragment.java, app/src/main/java/org/lsposed/manager/ui/fragment/ModulesFragment.java, app/src/main/java/org/lsposed/manager/ui/fragment/RepoFragment.java, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/strings.xml
=> [app] Show upgradable modules on front page

core/src/main/java/android/content/res/XResources.java
=> Init resources hook when call SystemWideReplace

core/src/main/java/org/lsposed/lspd/service/ConfigFileManager.java, core/src/main/java/org/lsposed/lspd/service/LogcatService.java, hiddenapi-bridge/src/main/java/hidden/HiddenApiBridge.java, hiddenapi-stubs/src/main/java/android/os/SELinux.java, hiddenapi-stubs/src/main/java/dalvik/system/VMRuntime.java
=> [core] Fix getprop

app/build.gradle.kts
=> [app] Update Dependencies

core/src/main/java/org/lsposed/lspd/service/LSPosedService.java, core/src/main/java/org/lsposed/lspd/service/PackageService.java
https://android.googlesource.com/platform/frameworks/base/+/e74e961711cf83c97d26d55f1698fe96bbae4064%5E%21/
=> [core] Don't trust EXTRA_REMOVED_FOR_ALL_USERS

core/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, hiddenapi-stubs/src/main/java/android/view/IWindowManager.java
=> Lock screen unconditionally after switching user

core/build.gradle.kts, core/magisk_module/post-fs-data.sh
To be compatible with https://github.com/topjohnwu/Magisk/commit/fef44bd24f817e4d605249dca9c979014395f80d
=> Dont launch lspd when flavor not match

app/src/main/java/org/lsposed/manager/ui/fragment/RepoFragment.java, app/src/main/res/menu/menu_repo.xml, app/src/main/res/values/strings.xml
=> [app] Upgradable first on repo page

core/src/main/java/android/content/res/XResources.java
1. Fix missing `getFloat` overload for XResources
2. Fix missing `getFont` overload
3. Add `getValue` and `getValueForDensity` replacement for apps that
obtain raw values
Fix #1525
=> Enhance resources hook

daemon/src/main/cpp/logcat.cpp
=> Avoid frequently wait if log tag prop not found

core/build.gradle.kts, core/magisk_module/service.sh, daemon/src/main/java/org/lsposed/lspd/service/LSPSystemServerService.java, daemon/src/main/java/org/lsposed/lspd/service/ServiceManager.java
=> Try to restart zygote if injection fails

app/src/main/java/org/lsposed/manager/ui/fragment/CompileDialogFragment.java
Fragment may have detached and does not have parent fragment manager
=> Fix IllegalStateException

core/src/main/cpp/main/include/logging.h, core/src/main/java/org/lsposed/lspd/service/BridgeService.java, core/src/main/java/org/lsposed/lspd/service/ParcelUtils.java
=> Support HarmonyOS

app/src/main/java/org/lsposed/manager/adapters/ScopeAdapter.java, app/src/main/java/org/lsposed/manager/ui/fragment/ModulesFragment.java, app/src/main/java/org/lsposed/manager/ui/fragment/RepoFragment.java, app/src/main/java/org/lsposed/manager/ui/fragment/RepoItemFragment.java
=> set rv items and notify change in the same thread

app/src/main/java/org/lsposed/manager/ui/activity/base/BaseActivity.java
=> Fix black theme when customizing color schema

core/magisk_module/customize.sh, core/magisk_module/daemon, core/magisk_module/post-fs-data.sh, core/magisk_module/service.sh, core/src/main/cpp/main/src/jni/yahfa.cpp, core/src/main/java/org/lsposed/lspd/yahfa/dexmaker/HookerDexMaker.java
=> Unshare `/data/resource-cache`

app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java
=> Fix language switch for Application context

core/src/main/cpp/main/api/zygisk_main.cpp, core/src/main/cpp/main/src/service.cpp, core/src/main/java/org/lsposed/lspd/core/Main.java, core/src/main/java/org/lsposed/lspd/hooker/HandleSystemServerProcessHooker.java, core/src/main/java/org/lsposed/lspd/hooker/StartBootstrapServicesHooker.java, hiddenapi-stubs/src/main/java/com/android/internal/os/ZygoteInit.java
=> Fix `systemMain` being inlined in Android 13

daemon/src/main/java/org/lsposed/lspd/service/ServiceManager.java
=> Fix icon creation on ZUI

app/src/main/java/org/lsposed/manager/App.java
=> Fix activity relaunches constantly on WSA

core/magisk_module/daemon, core/src/main/cpp/main/api/zygisk_main.cpp, core/src/main/cpp/main/src/context.cpp, core/src/main/cpp/main/src/native_hook.cpp, core/src/main/cpp/main/src/symbol_cache.cpp, core/src/main/cpp/main/src/symbol_cache.h
=> Wait zygote socket before launching daemon

app/build.gradle.kts, build.gradle.kts, core/build.gradle.kts, daemon-service/build.gradle.kts, daemon/build.gradle.kts, hiddenapi/bridge/build.gradle.kts, settings.gradle.kts
Move common parts to root project
=> Refine gradle script

core/src/main/java/de/robv/android/xposed/XposedBridge.java, core/src/main/java/de/robv/android/xposed/callbacks/XC_LayoutInflated.java
=> Fix array cast

app/src/main/java/org/lsposed/manager/ui/fragment/RecyclerViewDialogFragment.java, gradle.properties
and upgrade androidx navigation to 2.5.0-alpha04
=> Fix a ui bug & upgrade AGP to 7.1.3

app/src/main/java/org/lsposed/manager/ui/dialog/BlurBehindDialogBuilder.java
=> Fix blur effect on Android 12

core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java, daemon/src/main/java/org/lsposed/lspd/service/ConfigManager.java
=> Skip duplicate scopes for module process

core/src/main/java/de/robv/android/xposed/callbacks/XC_LayoutInflated.java
=> `XC_LayoutInflated` should be comparable

magisk-loader/src/main/jni/src/magisk_loader.cpp, magisk-loader/src/main/jni/src/service.cpp
=> Fix Ref moved

daemon/src/main/jni/obfuscation.cpp
android.content.res.XmlResourceParser
NOT TESTED
=> fix:error obfuscate classes list

README.md, core/src/main/jni/include/elf_util.h, core/src/main/jni/src/elf_util.cpp, core/src/main/jni/src/jni/resources_hook.cpp, core/src/main/jni/src/symbol_cache.cpp, magisk-loader/magisk_module/module.prop, magisk-loader/src/main/jni/src/magisk_loader.cpp
=> Update elf util & lsplant to support A13B1 arm

app/build.gradle.kts
=> Revert "Bump mainswitchbar from 1.0.2 to 1.1.0"

magisk-loader/magisk_module/customize.sh
=> Fix zygisk x86 only installation

daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, daemon/src/main/java/org/lsposed/lspd/service/PackageService.java, services/manager-service/src/main/aidl/org/lsposed/lspd/ILSPManagerService.aidl
https://github.com/RikkaApps/RikkaX/tree/master/parcelablelist
=> Replace ParceledListSlice with ParcelableListSlice

daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java, hiddenapi/stubs/src/main/java/android/app/INotificationManager.java
=> Fix: "cancelNotificationWithTag" method difference when API below 30

external/CMakeLists.txt
=> Disable Dobby SymbolResolver

daemon/src/main/java/org/lsposed/lspd/service/ConfigManager.java
=> Replace corruption handler of DB

app/src/main/AndroidManifest.xml
=> Revert "AndroidManifest.xml: Prevent layout changed when soft input called"

core/src/main/jni/include/context.h
Exceptions should not be ignored
=> Let it crash

daemon/src/main/java/org/lsposed/lspd/service/LSPosedService.java
Signed-off-by: 5ec1cff <ewtqyqyewtqyqy@gmail.com>
=> Avoid calling `finishReceiver` for unordered broadcasts

app/src/main/java/org/lsposed/manager/ui/fragment/BaseFragment.java
Check if fab is show before setAnchorView
=> Fix snackbar not showing

magisk-loader/magisk_module/util_functions.sh
=> Revert "Reject installation when JsHook is installed"

app/src/main/java/org/lsposed/manager/repo/RepoLoader.java
https://github.com/Xposed-Modules-Repo/modules/commit/16d77a8de6f436f4611659f346d3345b88b254a6
=> replace vername's space checking module upgrade

core/src/main/java/android/content/res/XResources.java
=> Init resources hook when call hookSystemWideLayout

core/src/main/jni/src/jni/hook_bridge.cpp
=> Revert "Guard backup during hook"

app/src/main/java/org/lsposed/manager/ui/widget/ScrollWebView.java
=> Fix ScrollWebView

daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java
=> Fix webview permission

README.md, gradle.properties, magisk-loader/magisk_module/util_functions.sh
Magisk 23 is missing some SELinux policies
Upgrade AGP to 7.4.1
=> All flavors require Magisk 24.0+

magisk-loader/src/main/java/org/lsposed/lspd/service/ActivityController.java
=> Support Android 14 DP1

daemon/src/main/java/org/lsposed/lspd/service/PackageService.java
=> Annotation Nullable

build.gradle.kts
=> Implment morden Xposed API

app/src/main/java/org/lsposed/manager/App.java, magisk-loader/src/main/java/org/lsposed/lspd/service/ActivityController.java
close #2433 
But the notification cannot send broadcast now.
=> Support Android 14 DP2

daemon/src/main/java/org/lsposed/lspd/service/LSPosedService.java
see https://developer.android.google.cn/reference/android/content/Context#RECEIVER_NOT_EXPORTED
=> fix android 13+ secret_code

app/src/main/java/org/lsposed/manager/ui/activity/MainActivity.java, app/src/main/java/org/lsposed/manager/ui/dialog/WelcomeDialog.java, app/src/main/java/org/lsposed/manager/ui/fragment/SettingsFragment.java, app/src/main/java/org/lsposed/manager/util/ShortcutUtil.java, app/src/main/res/values/strings.xml
=> Unconditional allow create shortcut except default desktop is not supported

.github/workflows/core.yml, build.gradle.kts, core/src/main/jni/CMakeLists.txt, daemon/build.gradle.kts, magisk-loader/build.gradle.kts
=> Revert "Let AGP to strip native libs"

gradle.properties
Starting with AGP 8.0 enableNewResourceShrinker enforced to true
=> Remove experimental enableNewResourceShrinker flags

app/src/main/java/org/lsposed/manager/ui/activity/CrashReportActivity.java
Same as: 0ee9e8a5f74ec25c01f98f25b900609ec3cf8380
=> Fix CrashReportActivity theme

daemon/src/main/java/org/lsposed/lspd/service/BridgeService.java, daemon/src/main/java/org/lsposed/lspd/service/LSPNotificationManager.java
Add more logs for LSPNotificationManager
Seteuid to 1000
This reverts commit 0a269930395422be930e381989c7c553c878ba58.
=> Set EUID to 1000 to fix notification and get modules list for Flyme

core/src/main/java/org/lsposed/lspd/hooker/OpenDexFileHooker.java
It may fail because of race, so try more as a temporary workaround
=> Try three times when setting classloader trusted

.github/workflows/core.yml, daemon/build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
This reverts commit 03d2cea093db056d56dbbea2ee13831e3dc5253a
=> Revert "Use source dependencies instead of mavenLocal (#2445)"

.github/workflows/core.yml
org.gradle.vfs.watch true by default
=> Remove out-date prop

daemon/src/main/java/org/lsposed/lspd/service/LSPModuleService.java
fix https://github.com/libxposed/example/issues/2
=> Fix wrong type casting in updateRemotePreferences

build.gradle.kts, daemon/build.gradle.kts, magisk-loader/build.gradle.kts
gradle/gradle#20210
gradle/gradle#24820
=> buildDir deprecated, use layout.buildDirectory instead

app/src/main/java/org/lsposed/manager/util/AppModule.java
The shrunken icon didn't look good, so decided to disable it unconditionally
=> Don't shrink non-AdaptiveIcons

daemon/src/main/java/org/lsposed/lspd/service/LSPModuleService.java, hiddenapi/stubs/src/main/java/android/content/IContentProvider.java
=> Fix `IContentProvider` for Android P and below
